#!/usr/bin/env python

# -*- mode: python -*-

import sys
import os

PROGNAME = os.path.basename(sys.argv[0])

def usage():
    print >> sys.stderr, ("Usage: %s hex-offset hex-length in-file out-file" % (PROGNAME))
    return 1

def main():
    if (len(sys.argv) - 1) != 4:
        return usage()

    offset = int(sys.argv[1], 16)
    length = int(sys.argv[2], 16)
    filename = sys.argv[3]
    outfile = sys.argv[4]

    if (offset < 0) or (length < 0):
        raise ValueError, "Neither offset or length can be negative"

    chunk = None
    with open(filename, "rb") as f:
        f.seek(offset)
        chunk = f.read(length)

    if len(chunk) < length:
        amt = length - len(chunk)
        print >> sys.stderr, ("%s is %iB smaller than requested" % (outfile, amt))

    with open(outfile, "wb+") as f:
        f.write(chunk)
    return 0

if __name__ == '__main__':
    sys.exit(main())
