#!/usr/bin/env python

import sys

NUM_ARGS = 4

if (len(sys.argv) - 1) != 4:
    print >> sys.stderr, ("%s: [hex-offset] [hex-length] [in-file] [out-file]"
                          % (sys.argv[0]))
    sys.exit(0)

offset = int(sys.argv[1], 16)
length = int(sys.argv[2], 16)
filename = sys.argv[3]
outfile = sys.argv[4]

if (offset < 0) or (length < 0):
    raise ValueError, "Neither offset or length can be negative"

chunk = None
with open(filename, "rb") as f:
    f.seek(offset)
    chunk = f.read(length)

if len(chunk) < length:
    amt = length - len(chunk)
    print >> sys.stderr, ("%s is %iB smaller than requested" % (outfile, amt))

with open(outfile, "wb+") as f:
    f.write(chunk)
