#!/usr/bin/env python

# -*- mode: python -*-

import sys
import os

PROGNAME = os.path.basename(sys.argv[0])

if (len(sys.argv) - 1) == 0:
    print >> sys.stderr, ("Usage: %s hex-string file" % (PROGNAME))
    sys.exit(0)

hexstring = sys.argv[1]
file = sys.argv[2]

string = ""
hexstring = [hexstring[hexidx:hexidx + 2]
             for hexidx in range(0, len(hexstring), 2)]
for hex in hexstring:
    string += "\\x%s" % (hex)

with open(file, "w+") as f:
    print >> f, string.decode('string_escape'),
