#!/usr/bin/env python

# -*- mode: python -*-

import sys
import os

PROGNAME = os.path.basename(sys.argv[0])

def main():
    if len(sys.argv) < 2:
        print >> sys.stderr, "lba2offset lba"
        sys.exit(0)

    lba = int(sys.argv[1])
    print "0x%08X" % ((lba * 2352) + 0x10)
    return 0

if __name__ == '__main__':
    sys.exit(main())
